SIMILARITY_THRESHOLD = 80

# Global debug flags - Set these to True to enable debugging
DEBUG_SIMILARITY = False
DEBUG_CALCULATE_DIFFERENCES = False
DEBUG_ALIGN_CONTOURS = False
USE_COMPARISON_MODEL = False
REFINEMENT_THRESHOLD = 0.1