FONT = "Segoe UI"

MATERIAL_BUTTON_PRIMARY_COLOR = "#6750A4"
MATERIAL_BUTTON_LIGHTER_COLOR = "#7F5AD9"
MATERIAL_BUTTON_DARKER_COLOR = "#543999"
MATERIAL_BUTTON_DISABLED_BG_COLOR = "#E8DEF8"
MATERIAL_BUTTON_DISABLED_TEXT_COLOR = "#79747E"
MATERIAL_BUTTON_TEXT_COLOR = "#FFFFFF"
