from enum import Enum, auto


class RobotServiceState(Enum):
    INITIALIZING = auto()
    MOVING_TO_FIRST_POINT = auto()
    WAIT_FOR_PATH_COMPLETION = auto()
    IDLE = auto()
    STARTING = auto()
    PREPARING_PATH = auto()
    MOVING_TO_START_POINT = auto()
    WAITING_FOR_START_REACH = auto()
    EXECUTING_PATH = auto()
    STARTING_PUMP = auto()
    SENDING_PATH_POINTS = auto()
    WAITING_PATH_COMPLETION = auto()
    STOPPING_PUMP = auto()
    TRANSITION_BETWEEN_PATHS = auto()
    PATH_CLEANUP = auto()
    PATH_INCREMENT = auto()
    COMPLETED = auto()
    ERROR = auto()
    STOPPED = auto()
    PAUSED = auto()
    STARTING_PUMP_ADJUSTMENT_THREAD = auto()
    PUMP_INITIAL_BOOST = auto()
