from enum import Enum

class Message(Enum):
    # Setup
    SETUP_FIRST_STEP = "Please press the blue button."
    SETUP_SECOND_STEP = "Home ROBOT"
    ENTER_ID_AND_PASSWORD = "Enter id and password IN BULGARIAN"
    INVALID_LOGIN_ID = "Invalid ID"
    SCAN_QR_TO_LOGIN = "Scan QR Code to Login"
    INCORRECT_PASSWORD = "Incorrect password."
    USER_NOT_FOUND = "User not found."

    # Login
    NEXT = "Next"
    PASSWORD = "PASSWORD"
    ID = "ID"
    LOGIN = "Login"
    HOME_ROBOT = "Home Robot"
    BACK = "BACK"
    ERROR_HOMING = "ERROR HOMING"
    USER = "USER"
    FIRST_NAME = "FIRST NAME"
    LAST_NAME = "LAST NAME"
    ROLE = "ROLE"
    EMAIL = "EMAIL"
    LOGIN_TIME = "LOGIN TIME"
    SESSION_DURATION = "SESSION DURATION"
    WARNING = "WARNING"
    THE_ROBOT_WILL_START_MOVING_TO_THE_LOGIN_POSITION = "THE ROBOT WILL START MOVING TO THE LOGIN POSITION."
    PLEASE_ENSURE_THE_AREA_IS_CLEAR_BEFORE_PROCEEDING = "Please ensure the area is clear before proceeding."
    # Main Window
    WORK = "Work"
    SERVICE = "Service"
    ADMINISTRATION = "Administration"
    STATISTICS = "Statistics"

    # Dashboard
    START = "Start"
    STOP = "Stop"
    PAUSE = "Pause"
    CLEAN = "Clean"
    GLUE = "Glue"

    # User Management
    UNKNOWN = "Unknown"
    ADD_USER = "Add User"
    EDIT_USER = "Edit User"
    DELETE_USER = "Delete User"
    REFRESH = "Refresh"
    READY = "Ready"
    GENERATE_QR = "Generate QR"
    LOADED = "Loaded"
    ERROR_LOADING_USERS = "Error loading users"
    ADD_NEW_USER = "Add New User"
    ADDED_SUCCESSFULLY = "added successfully"
    UPDATED_SUCCESSFULLY = "updated successfully"
    UPDATED_DELETED = "deleted successfully"
    USER_ALREADY_EXISTS = "User already exists"
    USERS_FOUND = "users found"
    ERROR_ADDING_USER = "Error adding user"
    ERROR_UPDATING_USER = "Error updating user"
    ERROR_DELETING_USER = "Error deleting user"
    ERROR_APPYING_FILTER = "Error applying filter"
    PLEASE_SELECT_USER_TO_EDIT = "Please select a user to edit"
    PLEASE_SELECT_USER_TO_DELETE = "Please select a user to delete"
    PLEASE_SELECT_USER_TO_GENERATE_QR_CODE = "Please select a user to generate a QR code"
    CONFIRM_DELETE = "Confirm Delete"
    ARE_YOU_SURE_YOU_WANT_TO_DELETE_USER = "Are you sure you want to delete user"
    SAVE = "Save"
    CANCEL = "Cancel"
    ID_MUST_BE_VALID_NUMBER = "ID must be a valid number"
    ALL_FIELDS_ARE_REQUIRED = "All fields are required"
    USER_MANAGEMENT = "User Management"
    FILTER_USERS = "Filter Users"
    FILTER_BY = "Filter by"
    FILTER_APPLIED = "Filter applied"
    ALL = "All"
    ERROR = "Error"
    QR_CODE = "QR Code"
    INFORMATION = "Information"
    ENTER_FILTER_VALUE = "Enter filter value..."
    APPLY_FILTERS = "Apply Filter"
    CLEAR_FILTERS = "Clear Filter"

    # Glue Meter Card
    ENTER_G_PER_M = "Enter g/m"
    ENTER_G_PER_SQUARE_M = "Enter g/m²"

    # Gallery
    SELECT_DATE_RANGE = "Select Date Range"
    FROM = "From"
    TO = "To"

    # Glue Settings View
    SPRAY_SETTINGS = "Spray Settings"
    SPRAY_WIDTH = "Spray Width"
    SPRAYING_HEIGHT = "Spraying Height"
    FAN_SPEED = "Fan Speed"
    GENERATOR_TO_GLUE_DELAY = "Generator to Glue Delay"
    MOTOR_SETTINGS = "Pump Settings"
    MOTOR_SPEED = "Motor Speed"
    REVERSE_STEPS = "Reverse Steps"
    REVERSE_DURATION = "Reverse Duration"
    REVERSE_SPEED = "Reverse Speed"
    GENERAL_SETTINGS = "General Settings"
    RZ_ANGLE = "RZ Angle"
    GLUE_TYPE = "Glue Type"
    DEVICE_CONTROL = "Device Control"
    MOTOR_CONTROL = "Motor Control"
    RELAY_CONTROL = "Relay Control"
    RELAY = "Relay"
    OTHER_SETTINGS = "Other Settings"
    GENERATOR = "Generator"
    FAN = "Fan"
    MOTOR = "Motor"
    DISPENSE_GLUE = "Dispense Glue"
    GENERATOR_TIMEOUT = "Generator Timeout"
    #--
    REFRESH_MOTORS_STATES = "Refresh Motors States"
    REFRESH_GENERATOR_STATE = "Refresh Generator State"
    REFRESH_FAN_STATE = "Refresh Fan State"
    TIMEOUT_BEFORE_MOTION = "Timeout Before Motion"
    REACH_START_THRESHOLD = "Reach Start Threshold"

    # CAMERA SETTINGS VIEW #
    CAMERA_STATUS = "Camera Status"
    CAMERA_SETTINGS = "Camera Settings"
    CAMERA_INDEX = "Camera Index"
    WIDTH = "Width"
    HEIGHT = "Height"
    SKIP_FRAMES = "Skip Frames"
    CONTOUR_DETECTION = "Contour Detection"
    ENABLE_DETECTION = "Enable Detection"
    DRAW_CONTOURS = "Draw Contours"
    THRESHOLD = "Threshold"
    EPSILON = "Epsilon"
    MIN_CONTOUR_AREA = "Min Contour Area"
    MAX_CONTOUR_AREA = "Max Contour Area"
    PREPROCESSING = "Preprocessing"
    GAUSSIAN_BLUR = "Gaussian Blur"
    BLUR_KERNEL_SIZE = "Blur Kernel Size"
    THRESHOLD_TYPE = "Threshold Type"
    DILATE = "Dilate"
    DILATE_KERNEL = "Dilate Kernel"
    DILATE_ITERATIONS = "Dilate Iterations"
    ERODE = "Erode"
    ERODE_KERNEL = "Erode Kernel"
    ERODE_ITERATIONS = "Erode Iterations"
    CALIBRATION = "Calibration"
    CHESSBOARD_WIDTH = "Chessboard Width"
    CHESSBOARD_HEIGHT = "Chessboard Height"
    SQUARE_SIZE = "Square Size"
    BRIGHTNESS_CONTROL = "Brightness Control"
    AUTO_BRIGHTNESS = "Auto Brightness"
    TARGET_BRIGHTNESS = "Target Brightness"
    ARUCO_DETECTION = "Aruco Detection"
    ENABLE_ARUCO = "Enable Aruco"
    DICTIONARY = "Dictionary"
    FLIP_IMAGE = "Flip Image"
    EXIT_RAW_MODE = "Exit Raw Mode"
    RAW_MODE = "Raw Mode"

    # ROBOT SETTINGS VIEW #
    ROBOT_INFORMATION = "Robot Information"
    ROBOT_TOOL = "Tool"
    ROBOT_USER = "User"
    TCP_X_OFFSET = "TCP X Offset"
    TCP_Y_OFFSET = "TCP Y Offset"
    SAFETY_LIMITS = "Safety Limits"
    GLOBAL_MOTION_SETTINGS = "Global Motion Settings"
    GLOBAL_VELOCITY = "Global Velocity"
    GLOBAL_ACCELERATION = "Global Acceleration"
    VELOCITY = "Velocity"
    ACCELERATION = "Acceleration"
    POSITION = "Position"
    LOGIN_POSITION = "Login Position"
    CALIBRATION_POSITION = "Calibration Position"
    WORKPIECE_POSITION = "Workpiece Position"
    NOZZLE_CLEANING_POSITIONS = "Nozzle Cleaning Positions"
    TOOL_CHANGER_POSITION = "Tool Changer Position"
    SLOT = "Slot"
    PICKUP_POSITIONS = "Pickup Positions"
    DROP_POSITIONS = "Drop Positions"
    ADD = "Add"
    REMOVE = "Remove"
    EDIT = "Edit"
    MOVE_TO = "Move to"
    SAVE_CURRENT_POSITION = "Save Current Position"
    EXECUTE_TRAJECTORY = "Execute Trajectory"

    # Feedback Messages
    PLACE_CALIBRATION_PATTERN = "Please place the calibration pattern in view of the camera."
    CALIBRATION_SUCCESSFUL = "Calibration completed successfully."
    CALIBRATION_FAILED = "Calibration failed. Please try again."
    FAILED_TO_SEND_COMMAND_TO_ROBOT = "Failed to send command to robot."
    NO_CONTOURS_DETECTED = "No contours detected."
    NO_WORKPIECE_DETECTED = "No workpiece detected."